weights: ./runs/train/yolov5l_results3/weights/last.pt
cfg: ''
data: data/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 120
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: yolov5l_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/yolov5l_results3
